version: '3'

services:
  jackett_new:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett_new
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true
    volumes:
      - ./data:/config
      - ./blackhole:/downloads
    ports:
      - 9217:9117
    restart: unless-stopped


  flaresolverr_new:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr_new
    environment:
      - TZ=Europe/London
    ports:
      - 8291:8191
    restart: unless-stopped
