name: stremio_jacket
services:
  flaresolverr_new:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr_new
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=$(id -u)
      - PGID=$(id -g)
      - TZ=America/Los_Angeles
#    networks:
#      - stremio_jacket_network
    ports:
      - "${PORT:-8291}:8191"
    restart: unless-stopped
  jackett_new:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett_new
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - TZ=America/Los_Angeles
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    depends_on:
      - flaresolverr_new
#    networks:
#      - stremio_jacket_network
    volumes:
      - ./data:/config
      - /path/to/blackhole:/downloads
    ports:
      - 9217:9117
    restart: unless-stopped
  jackett-stremio_new:
    image: belmeg/stremio-addon-jackett
    container_name: jackett-stremio_new
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - TZ=America/Los_Angeles
      - ADDON_NAME=stremio_jacket
    depends_on:
      - jackett_new
#    networks:
#      - stremio_jacket_network
    ports:
      - 3100:3000
    restart: unless-stopped

#networks:
#    stremio_jacket_network:
#        external: true
#        name: stremio_jacket_network
