version: "3"

services:
    traefik_new:
        image: "traefik:v2.5"
        container_name: "traefik_new"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /etc/traefik:/etc/traefik
            - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: unless-stopped
